// 單字資料庫
const vocabData = [
    // --- U6 單字 ---
    { id: 101, unit: "U6", en: "apartment", ph: "[ə`partmənt]", zh: "公寓" },
    { id: 102, unit: "U6", en: "glad", ph: "[glæd]", zh: "高興的" },
    { id: 103, unit: "U6", en: "town", ph: "[taʊn]", zh: "城鎮" },
    { id: 104, unit: "U6", en: "polite", ph: "[pə`laɪt]", zh: "有禮貌的" },
    { id: 105, unit: "U6", en: "seat", ph: "[sit]", zh: "座位" },
    { id: 106, unit: "U6", en: "beside", ph: "[bɪ`saɪd]", zh: "在...旁邊" },
    { id: 107, unit: "U6", en: "except", ph: "[ɪk`sɛpt]", zh: "除了" },
    { id: 108, unit: "U6", en: "blank", ph: "[blæŋk]", zh: "空白(的)" },
    { id: 109, unit: "U6", en: "present", ph: "[`prɛzṇt]", zh: "禮物" },
    { id: 110, unit: "U6", en: "invite", ph: "[ɪn`vaɪt]", zh: "邀請" },
    { id: 111, unit: "U6", en: "perhaps", ph: "[pə`hæps]", zh: "或許" },
    { id: 112, unit: "U6", en: "kiss", ph: "[kɪs]", zh: "吻" },
    { id: 113, unit: "U6", en: "side", ph: "[saɪd]", zh: "側面；邊" },
    { id: 114, unit: "U6", en: "sidewalk", ph: "[`saɪd,wɔk]", zh: "人行道" },
    { id: 115, unit: "U6", en: "blind", ph: "[blaɪnd]", zh: "盲的" },
    { id: 116, unit: "U6", en: "April Fools' Day", ph: "[`eprəl `fulz ,de]", zh: "愚人節" },
    { id: 117, unit: "U6", en: "tape", ph: "[tep]", zh: "用膠帶黏貼；膠帶" },
    { id: 118, unit: "U6", en: "paper", ph: "[`pepɚ]", zh: "紙" },
    { id: 119, unit: "U6", en: "joke", ph: "[dʒok]", zh: "玩笑；笑話" },
    { id: 120, unit: "U6", en: "visitor", ph: "[`vɪzɪtɚ]", zh: "遊客；參觀者" },
    { id: 121, unit: "U6", en: "somewhere", ph: "[`sʌm,(h)wɛr]", zh: "在某處" },
    { id: 122, unit: "U6", en: "mud", ph: "[mʌd]", zh: "泥土" },
    { id: 123, unit: "U6", en: "ahead", ph: "[ə`hɛd]", zh: "在前方" },
    { id: 124, unit: "U6", en: "heat", ph: "[hit]", zh: "高溫；加熱" },
    { id: 125, unit: "U6", en: "rise", ph: "[raɪz]", zh: "升起；起身" },
    { id: 126, unit: "U6", en: "rich", ph: "[rɪtʃ]", zh: "富有的" },
    { id: 127, unit: "U6", en: "lazy", ph: "[`lezɪ]", zh: "懶惰的；慵懶的" },
    { id: 128, unit: "U6", en: "have bigger fish to fry", ph: "[hæv `bɪgɚ ,fɪʃ tə `fraɪ]", zh: "有更重要的事要做" },
    { id: 129, unit: "U6", en: "smoke", ph: "[smok]", zh: "煙霧；抽菸" },
    { id: 130, unit: "U6", en: "cover", ph: "[`kʌvɚ]", zh: "覆蓋；遮蓋(物)" },
    { id: 131, unit: "U6", en: "used to", ph: "[`just tə]", zh: "過去時常..." },
    { id: 132, unit: "U6", en: "appear", ph: "[ə`pɪr]", zh: "似乎" },
    { id: 133, unit: "U6", en: "serious", ph: "[`sɪrɪəs]", zh: "認真的" },
    { id: 134, unit: "U6", en: "lie", ph: "[laɪ]", zh: "躺；臥" },
    { id: 135, unit: "U6", en: "draw", ph: "[drɔ]", zh: "提取 (水、錢)" },
    { id: 136, unit: "U6", en: "spell", ph: "[spɛl]", zh: "咒語" },
    { id: 137, unit: "U6", en: "worthless", ph: "[`wɜθlɪs]", zh: "無價值的" },
    { id: 138, unit: "U6", en: "chat", ph: "[tʃæt]", zh: "聊天" },
    { id: 139, unit: "U6", en: "resist", ph: "[rɪ`zɪst]", zh: "抵抗" },
    { id: 140, unit: "U6", en: "complain", ph: "[kəm`plen]", zh: "抱怨" },
    { id: 141, unit: "U6", en: "fairy", ph: "[`fɛrɪ]", zh: "精靈；仙子" },
    { id: 142, unit: "U6", en: "jewel", ph: "[`dʒuəl]", zh: "寶石" },

    // --- U5 單字 ---
    { id: 1, unit: "U5", en: "arrive", ph: "[ə`raɪv]", zh: "抵達" },
    { id: 2, unit: "U5", en: "planet", ph: "[`plænɪt]", zh: "行星" },
    { id: 3, unit: "U5", en: "line", ph: "[laɪn]", zh: "隊伍；直線" },
    { id: 4, unit: "U5", en: "appear", ph: "[ə`pɪr]", zh: "出現" },
    { id: 5, unit: "U5", en: "restroom", ph: "[`rɛst,rum]", zh: "洗手間" },
    { id: 6, unit: "U5", en: "bath", ph: "[bæθ]", zh: "沐浴" },
    { id: 7, unit: "U5", en: "uniform", ph: "[`junə,fɔrm]", zh: "制服" },
    { id: 8, unit: "U5", en: "tail", ph: "[tel]", zh: "尾巴" },
    { id: 9, unit: "U5", en: "bottom", ph: "[`bɑtəm]", zh: "臀部；底部" },
    { id: 10, unit: "U5", en: "main", ph: "[men]", zh: "主要的" },
    { id: 11, unit: "U5", en: "notice", ph: "[`notɪs]", zh: "注意到；告示" },
    { id: 12, unit: "U5", en: "belong", ph: "[bə`lɔŋ]", zh: "屬於" },
    { id: 13, unit: "U5", en: "square", ph: "[skwɛr]", zh: "正方形(的)" },
    { id: 14, unit: "U5", en: "string", ph: "[strɪŋ]", zh: "串；線" },
    { id: 15, unit: "U5", en: "round", ph: "[raʊnd]", zh: "圓形的" },
    { id: 16, unit: "U5", en: "dot", ph: "[dɑt]", zh: "圓點" },
    { id: 17, unit: "U5", en: "bow", ph: "[bo]", zh: "蝴蝶結" },
    { id: 18, unit: "U5", en: "pin", ph: "[pɪn]", zh: "飾針；胸針" },
    { id: 19, unit: "U5", en: "neighbor", ph: "[`nebɚ]", zh: "鄰居" },
    { id: 20, unit: "U5", en: "foreigner", ph: "[`fɔrɪnɚ]", zh: "外國人" },
    { id: 21, unit: "U5", en: "hobby", ph: "[`hɑbɪ]", zh: "嗜好" },
    { id: 22, unit: "U5", en: "businessman", ph: "[`bɪznɪsmæn]", zh: "商人" },
    { id: 23, unit: "U5", en: "business", ph: "[`bɪznɪs]", zh: "生意；事業" },
    { id: 24, unit: "U5", en: "dictionary", ph: "[`dɪkʃən,ɛrɪ]", zh: "字典" },
    { id: 25, unit: "U5", en: "workbook", ph: "[`wɝk,bʊk]", zh: "作業本" },
    { id: 26, unit: "U5", en: "born", ph: "[bɔrn]", zh: "出生的" },
    { id: 27, unit: "U5", en: "prize", ph: "[praɪz]", zh: "獎" },
    { id: 28, unit: "U5", en: "topic", ph: "[`tɑpɪk]", zh: "主題" },
    { id: 29, unit: "U5", en: "knowledge", ph: "[`nɑlɪdʒ]", zh: "知識" },
    { id: 30, unit: "U5", en: "public", ph: "[`pʌblɪk]", zh: "公眾(的)" },
    { id: 31, unit: "U5", en: "go on", ph: "[go `ɑn]", zh: "發生" },
    { id: 32, unit: "U5", en: "lead", ph: "[lid]", zh: "通往" },
    { id: 33, unit: "U5", en: "play", ph: "[ple]", zh: "扮演" },
    { id: 34, unit: "U5", en: "light", ph: "[laɪt]", zh: "輕的" },
    { id: 35, unit: "U5", en: "exercise", ph: "[`ɛksɚ,saɪz]", zh: "習題；練習" },
    { id: 36, unit: "U5", en: "be no stranger to", ph: "[bi no `strendʒɚ tə]", zh: "對...不陌生" },
    { id: 37, unit: "U5", en: "key", ph: "[ki]", zh: "關鍵(的)" },
    { id: 38, unit: "U5", en: "comic book convention", ph: "[`kɑmɪk ,bʊk kən`vɛnʃən]", zh: "漫畫展" },
    { id: 39, unit: "U5", en: "booth", ph: "[buθ]", zh: "攤位" },
    { id: 40, unit: "U5", en: "character", ph: "[`kærɪktɚ]", zh: "角色" },
    { id: 41, unit: "U5", en: "hug", ph: "[hʌg]", zh: "擁抱" },
    { id: 42, unit: "U5", en: "describe", ph: "[dɪ`skraɪb]", zh: "描述" },
    { id: 43, unit: "U5", en: "noun", ph: "[naʊn]", zh: "名詞" },
    { id: 44, unit: "U5", en: "pearl", ph: "[pɝl]", zh: "珍珠" },
    { id: 45, unit: "U5", en: "cosplayer", ph: "[`kɑz,pleɚ]", zh: "角色扮演者" },
    { id: 46, unit: "U5", en: "article", ph: "[`ɑrtɪk!]", zh: "文章" },
    { id: 47, unit: "U5", en: "meaning", ph: "[`minɪŋ]", zh: "意思" },
    { id: 48, unit: "U5", en: "anime", ph: "[`ænəme]", zh: "(日本的)動畫片" },
    { id: 49, unit: "U5", en: "artist", ph: "[`ɑrtɪst]", zh: "藝術家" },
    { id: 50, unit: "U5", en: "college", ph: "[`kɑlɪdʒ]", zh: "大學" },
    { id: 51, unit: "U5", en: "attention", ph: "[ə`tɛnʃən]", zh: "注意" },

    // --- U4 單字 (新增的 43 個) ---
    { id: 201, unit: "U4", en: "gate", ph: "[get]", zh: "大門" },
    { id: 202, unit: "U4", en: "file", ph: "[faɪl]", zh: "檔案" },
    { id: 203, unit: "U4", en: "quiz", ph: "[kwɪz]", zh: "小考" },
    { id: 204, unit: "U4", en: "blackboard", ph: "[`blæk,bɔrd]", zh: "黑板" },
    { id: 205, unit: "U4", en: "chalk", ph: "[tʃɔk]", zh: "粉筆" },
    { id: 206, unit: "U4", en: "screen", ph: "[skrin]", zh: "螢幕" },
    { id: 207, unit: "U4", en: "error", ph: "[`ɛrɚ]", zh: "錯誤" },
    { id: 208, unit: "U4", en: "button", ph: "[`bʌtṇ]", zh: "按鈕；鈕扣" },
    { id: 209, unit: "U4", en: "enter", ph: "[`ɛntɚ]", zh: "輸入；進入" },
    { id: 210, unit: "U4", en: "wake word", ph: "[`wek ,wɝd]", zh: "喚醒字詞" },
    { id: 211, unit: "U4", en: "whether", ph: "[`(h)wɛðɚ]", zh: "是否" },
    { id: 212, unit: "U4", en: "list", ph: "[lɪst]", zh: "清單；列出" },
    { id: 213, unit: "U4", en: "voice assistant", ph: "[`vɔɪs ə`sɪstənt]", zh: "語音助理" },
    { id: 214, unit: "U4", en: "machine", ph: "[mə`ʃin]", zh: "機器" },
    { id: 215, unit: "U4", en: "dozen", ph: "[`dʌzṇ]", zh: "(一)打" },
    { id: 216, unit: "U4", en: "refrigerator", ph: "[rɪ`frɪdʒə,retɚ]", zh: "冰箱" },
    { id: 217, unit: "U4", en: "upload", ph: "[ʌp`lod]", zh: "上傳" },
    { id: 218, unit: "U4", en: "e-mail", ph: "[`i,mel]", zh: "電子郵件" },
    { id: 219, unit: "U4", en: "key", ph: "[ki]", zh: "鑰匙" },
    { id: 220, unit: "U4", en: "shopkeeper", ph: "[`ʃɑp,kipɚ]", zh: "店主" },
    { id: 221, unit: "U4", en: "cellphone", ph: "[`sɛl,fon]", zh: "手機" },
    { id: 222, unit: "U4", en: "collect", ph: "[kə`lɛkt]", zh: "收集" },
    { id: 223, unit: "U4", en: "outside", ph: "[`aʊt`saɪd]", zh: "在外面；外面(的)" },
    { id: 224, unit: "U4", en: "wallet", ph: "[`wɑlɪt]", zh: "錢包" },
    { id: 225, unit: "U4", en: "couch", ph: "[kaʊtʃ]", zh: "沙發" },
    { id: 226, unit: "U4", en: "lamp", ph: "[læmp]", zh: "檯燈" },
    { id: 227, unit: "U4", en: "program", ph: "[`progræm]", zh: "節目" },
    { id: 228, unit: "U4", en: "modern", ph: "[`mɑdɚn]", zh: "現代的" },
    { id: 229, unit: "U4", en: "cross that bridge when one comes to it", ph: "[krɔs ðæt brɪdʒ hwen wʌn kʌmz tu ɪt]", zh: "船到橋頭自然直" },
    { id: 230, unit: "U4", en: "honey", ph: "[`hʌnɪ]", zh: "親愛的" },
    { id: 231, unit: "U4", en: "save", ph: "[sev]", zh: "儲存" },
    { id: 232, unit: "U4", en: "through", ph: "[θru]", zh: "透過；憑藉" },
    { id: 233, unit: "U4", en: "if", ph: "[ɪf]", zh: "是否" },
    { id: 234, unit: "U4", en: "not... anymore", ph: "[nɑt ... `ɛnɪmɔr]", zh: "不再..." },
    { id: 235, unit: "U4", en: "the cloud", ph: "[ðə `klaʊd]", zh: "雲端" },
    { id: 236, unit: "U4", en: "type", ph: "[taɪp]", zh: "打字" },
    { id: 237, unit: "U4", en: "stand for", ph: "[`stænd fɔr]", zh: "代表" },
    { id: 238, unit: "U4", en: "set", ph: "[sɛt]", zh: "設定" },
    { id: 239, unit: "U4", en: "shape", ph: "[ʃep]", zh: "塑造" },
    { id: 240, unit: "U4", en: "code", ph: "[kod]", zh: "碼" },
    { id: 241, unit: "U4", en: "connect", ph: "[kə`nɛkt]", zh: "連接" },
    { id: 242, unit: "U4", en: "product", ph: "[`prɑdʌkt]", zh: "產品" },
    { id: 243, unit: "U4", en: "everywhere", ph: "[`ɛvrɪ,hwɛr]", zh: "到處" }
];
