// 單字資料庫
// 若要新增單字，請複製一行，修改 id, en, ph, zh 即可
const vocabData = [
    { id: 1, en: "apartment", ph: "[ə`partmənt]", zh: "公寓" },
    { id: 2, en: "glad", ph: "[glæd]", zh: "高興的" },
    { id: 3, en: "town", ph: "[taʊn]", zh: "城鎮" },
    { id: 4, en: "polite", ph: "[pə`laɪt]", zh: "有禮貌的" },
    { id: 5, en: "seat", ph: "[sit]", zh: "座位" },
    { id: 6, en: "beside", ph: "[bɪ`saɪd]", zh: "在...旁邊" },
    { id: 7, en: "except", ph: "[ɪk`sɛpt]", zh: "除了" },
    { id: 8, en: "blank", ph: "[blæŋk]", zh: "空白(的)" },
    { id: 9, en: "present", ph: "[`prɛzṇt]", zh: "禮物" },
    { id: 10, en: "invite", ph: "[ɪn`vaɪt]", zh: "邀請" },
    { id: 11, en: "perhaps", ph: "[pə`hæps]", zh: "或許" },
    { id: 12, en: "kiss", ph: "[kɪs]", zh: "吻" },
    { id: 13, en: "side", ph: "[saɪd]", zh: "側面；邊" },
    { id: 14, en: "sidewalk", ph: "[`saɪd,wɔk]", zh: "人行道" },
    { id: 15, en: "blind", ph: "[blaɪnd]", zh: "盲的" },
    { id: 16, en: "April Fools' Day", ph: "[`eprəl `fulz ,de]", zh: "愚人節" },
    { id: 17, en: "tape", ph: "[tep]", zh: "用膠帶黏貼；膠帶" },
    { id: 18, en: "paper", ph: "[`pepɚ]", zh: "紙" },
    { id: 19, en: "joke", ph: "[dʒok]", zh: "玩笑；笑話" },
    { id: 20, en: "visitor", ph: "[`vɪzɪtɚ]", zh: "遊客；參觀者" },
    { id: 21, en: "somewhere", ph: "[`sʌm,(h)wɛr]", zh: "在某處" },
    { id: 22, en: "mud", ph: "[mʌd]", zh: "泥土" },
    { id: 23, en: "ahead", ph: "[ə`hɛd]", zh: "在前方" },
    { id: 24, en: "heat", ph: "[hit]", zh: "高溫；加熱" },
    { id: 25, en: "rise", ph: "[raɪz]", zh: "升起；起身" },
    { id: 26, en: "rich", ph: "[rɪtʃ]", zh: "富有的" },
    { id: 27, en: "lazy", ph: "[`lezɪ]", zh: "懶惰的；慵懶的" },
    { id: 28, en: "have bigger fish to fry", ph: "[hæv `bɪgɚ ,fɪʃ tə `fraɪ]", zh: "有更重要的事要做" },
    { id: 29, en: "smoke", ph: "[smok]", zh: "煙霧；抽菸" },
    { id: 30, en: "cover", ph: "[`kʌvɚ]", zh: "覆蓋；遮蓋(物)" },
    { id: 31, en: "used to", ph: "[`just tə]", zh: "過去時常..." },
    { id: 32, en: "appear", ph: "[ə`pɪr]", zh: "似乎" },
    { id: 33, en: "serious", ph: "[`sɪrɪəs]", zh: "認真的" },
    { id: 34, en: "lie", ph: "[laɪ]", zh: "躺；臥 (現在分詞為 lying)" },
    { id: 35, en: "draw", ph: "[drɔ]", zh: "提取 (水、錢)" },
    { id: 36, en: "spell", ph: "[spɛl]", zh: "咒語" },
    { id: 37, en: "worthless", ph: "[`wɜθlɪs]", zh: "無價值的" },
    { id: 38, en: "chat", ph: "[tʃæt]", zh: "聊天" },
    { id: 39, en: "resist", ph: "[rɪ`zɪst]", zh: "抵抗" },
    { id: 40, en: "complain", ph: "[kəm`plen]", zh: "抱怨" },
    { id: 41, en: "fairy", ph: "[`fɛrɪ]", zh: "精靈；仙子" },
    { id: 42, en: "jewel", ph: "[`dʒuəl]", zh: "寶石" }
];
