// 單字資料庫
const vocabData = [
    // ==========================================
    //               第五冊 (Book 5)
    // ==========================================

    // --- U6 單字 ---
    { id: 101, unit: "U6", en: "apartment", ph: "[ə`partmənt]", zh: "公寓" },
    { id: 102, unit: "U6", en: "glad", ph: "[glæd]", zh: "高興的" },
    { id: 103, unit: "U6", en: "town", ph: "[taʊn]", zh: "城鎮" },
    { id: 104, unit: "U6", en: "polite", ph: "[pə`laɪt]", zh: "有禮貌的" },
    { id: 105, unit: "U6", en: "seat", ph: "[sit]", zh: "座位" },
    { id: 106, unit: "U6", en: "beside", ph: "[bɪ`saɪd]", zh: "在...旁邊" },
    { id: 107, unit: "U6", en: "except", ph: "[ɪk`sɛpt]", zh: "除了" },
    { id: 108, unit: "U6", en: "blank", ph: "[blæŋk]", zh: "空白(的)" },
    { id: 109, unit: "U6", en: "present", ph: "[`prɛzṇt]", zh: "禮物" },
    { id: 110, unit: "U6", en: "invite", ph: "[ɪn`vaɪt]", zh: "邀請" },
    { id: 111, unit: "U6", en: "perhaps", ph: "[pə`hæps]", zh: "或許" },
    { id: 112, unit: "U6", en: "kiss", ph: "[kɪs]", zh: "吻" },
    { id: 113, unit: "U6", en: "side", ph: "[saɪd]", zh: "側面；邊" },
    { id: 114, unit: "U6", en: "sidewalk", ph: "[`saɪd,wɔk]", zh: "人行道" },
    { id: 115, unit: "U6", en: "blind", ph: "[blaɪnd]", zh: "盲的" },
    { id: 116, unit: "U6", en: "April Fools' Day", ph: "[`eprəl `fulz ,de]", zh: "愚人節" },
    { id: 117, unit: "U6", en: "tape", ph: "[tep]", zh: "用膠帶黏貼；膠帶" },
    { id: 118, unit: "U6", en: "paper", ph: "[`pepɚ]", zh: "紙" },
    { id: 119, unit: "U6", en: "joke", ph: "[dʒok]", zh: "玩笑；笑話" },
    { id: 120, unit: "U6", en: "visitor", ph: "[`vɪzɪtɚ]", zh: "遊客；參觀者" },
    { id: 121, unit: "U6", en: "somewhere", ph: "[`sʌm,(h)wɛr]", zh: "在某處" },
    { id: 122, unit: "U6", en: "mud", ph: "[mʌd]", zh: "泥土" },
    { id: 123, unit: "U6", en: "ahead", ph: "[ə`hɛd]", zh: "在前方" },
    { id: 124, unit: "U6", en: "heat", ph: "[hit]", zh: "高溫；加熱" },
    { id: 125, unit: "U6", en: "rise", ph: "[raɪz]", zh: "升起；起身" },
    { id: 126, unit: "U6", en: "rich", ph: "[rɪtʃ]", zh: "富有的" },
    { id: 127, unit: "U6", en: "lazy", ph: "[`lezɪ]", zh: "懶惰的；慵懶的" },
    { id: 128, unit: "U6", en: "have bigger fish to fry", ph: "[hæv `bɪgɚ ,fɪʃ tə `fraɪ]", zh: "有更重要的事要做" },
    { id: 129, unit: "U6", en: "smoke", ph: "[smok]", zh: "煙霧；抽菸" },
    { id: 130, unit: "U6", en: "cover", ph: "[`kʌvɚ]", zh: "覆蓋；遮蓋(物)" },
    { id: 131, unit: "U6", en: "used to", ph: "[`just tə]", zh: "過去時常..." },
    { id: 132, unit: "U6", en: "appear", ph: "[ə`pɪr]", zh: "似乎" },
    { id: 133, unit: "U6", en: "serious", ph: "[`sɪrɪəs]", zh: "認真的" },
    { id: 134, unit: "U6", en: "lie", ph: "[laɪ]", zh: "躺；臥" },
    { id: 135, unit: "U6", en: "draw", ph: "[drɔ]", zh: "提取 (水、錢)" },
    { id: 136, unit: "U6", en: "spell", ph: "[spɛl]", zh: "咒語" },
    { id: 137, unit: "U6", en: "worthless", ph: "[`wɜθlɪs]", zh: "無價值的" },
    { id: 138, unit: "U6", en: "chat", ph: "[tʃæt]", zh: "聊天" },
    { id: 139, unit: "U6", en: "resist", ph: "[rɪ`zɪst]", zh: "抵抗" },
    { id: 140, unit: "U6", en: "complain", ph: "[kəm`plen]", zh: "抱怨" },
    { id: 141, unit: "U6", en: "fairy", ph: "[`fɛrɪ]", zh: "精靈；仙子" },
    { id: 142, unit: "U6", en: "jewel", ph: "[`dʒuəl]", zh: "寶石" },

    // --- U5 單字 ---
    { id: 1, unit: "U5", en: "arrive", ph: "[ə`raɪv]", zh: "抵達" },
    { id: 2, unit: "U5", en: "planet", ph: "[`plænɪt]", zh: "行星" },
    { id: 3, unit: "U5", en: "line", ph: "[laɪn]", zh: "隊伍；直線" },
    { id: 4, unit: "U5", en: "appear", ph: "[ə`pɪr]", zh: "出現" },
    { id: 5, unit: "U5", en: "restroom", ph: "[`rɛst,rum]", zh: "洗手間" },
    { id: 6, unit: "U5", en: "bath", ph: "[bæθ]", zh: "沐浴" },
    { id: 7, unit: "U5", en: "uniform", ph: "[`junə,fɔrm]", zh: "制服" },
    { id: 8, unit: "U5", en: "tail", ph: "[tel]", zh: "尾巴" },
    { id: 9, unit: "U5", en: "bottom", ph: "[`bɑtəm]", zh: "臀部；底部" },
    { id: 10, unit: "U5", en: "main", ph: "[men]", zh: "主要的" },
    { id: 11, unit: "U5", en: "notice", ph: "[`notɪs]", zh: "注意到；告示" },
    { id: 12, unit: "U5", en: "belong", ph: "[bə`lɔŋ]", zh: "屬於" },
    { id: 13, unit: "U5", en: "square", ph: "[skwɛr]", zh: "正方形(的)" },
    { id: 14, unit: "U5", en: "string", ph: "[strɪŋ]", zh: "串；線" },
    { id: 15, unit: "U5", en: "round", ph: "[raʊnd]", zh: "圓形的" },
    { id: 16, unit: "U5", en: "dot", ph: "[dɑt]", zh: "圓點" },
    { id: 17, unit: "U5", en: "bow", ph: "[bo]", zh: "蝴蝶結" },
    { id: 18, unit: "U5", en: "pin", ph: "[pɪn]", zh: "飾針；胸針" },
    { id: 19, unit: "U5", en: "neighbor", ph: "[`nebɚ]", zh: "鄰居" },
    { id: 20, unit: "U5", en: "foreigner", ph: "[`fɔrɪnɚ]", zh: "外國人" },
    { id: 21, unit: "U5", en: "hobby", ph: "[`hɑbɪ]", zh: "嗜好" },
    { id: 22, unit: "U5", en: "businessman", ph: "[`bɪznɪsmæn]", zh: "商人" },
    { id: 23, unit: "U5", en: "business", ph: "[`bɪznɪs]", zh: "生意；事業" },
    { id: 24, unit: "U5", en: "dictionary", ph: "[`dɪkʃən,ɛrɪ]", zh: "字典" },
    { id: 25, unit: "U5", en: "workbook", ph: "[`wɝk,bʊk]", zh: "作業本" },
    { id: 26, unit: "U5", en: "born", ph: "[bɔrn]", zh: "出生的" },
    { id: 27, unit: "U5", en: "prize", ph: "[praɪz]", zh: "獎" },
    { id: 28, unit: "U5", en: "topic", ph: "[`tɑpɪk]", zh: "主題" },
    { id: 29, unit: "U5", en: "knowledge", ph: "[`nɑlɪdʒ]", zh: "知識" },
    { id: 30, unit: "U5", en: "public", ph: "[`pʌblɪk]", zh: "公眾(的)" },
    { id: 31, unit: "U5", en: "go on", ph: "[go `ɑn]", zh: "發生" },
    { id: 32, unit: "U5", en: "lead", ph: "[lid]", zh: "通往" },
    { id: 33, unit: "U5", en: "play", ph: "[ple]", zh: "扮演" },
    { id: 34, unit: "U5", en: "light", ph: "[laɪt]", zh: "輕的" },
    { id: 35, unit: "U5", en: "exercise", ph: "[`ɛksɚ,saɪz]", zh: "習題；練習" },
    { id: 36, unit: "U5", en: "be no stranger to", ph: "[bi no `strendʒɚ tə]", zh: "對...不陌生" },
    { id: 37, unit: "U5", en: "key", ph: "[ki]", zh: "關鍵(的)" },
    { id: 38, unit: "U5", en: "comic book convention", ph: "[`kɑmɪk ,bʊk kən`vɛnʃən]", zh: "漫畫展" },
    { id: 39, unit: "U5", en: "booth", ph: "[buθ]", zh: "攤位" },
    { id: 40, unit: "U5", en: "character", ph: "[`kærɪktɚ]", zh: "角色" },
    { id: 41, unit: "U5", en: "hug", ph: "[hʌg]", zh: "擁抱" },
    { id: 42, unit: "U5", en: "describe", ph: "[dɪ`skraɪb]", zh: "描述" },
    { id: 43, unit: "U5", en: "noun", ph: "[naʊn]", zh: "名詞" },
    { id: 44, unit: "U5", en: "pearl", ph: "[pɝl]", zh: "珍珠" },
    { id: 45, unit: "U5", en: "cosplayer", ph: "[`kɑz,pleɚ]", zh: "角色扮演者" },
    { id: 46, unit: "U5", en: "article", ph: "[`ɑrtɪk!]", zh: "文章" },
    { id: 47, unit: "U5", en: "meaning", ph: "[`minɪŋ]", zh: "意思" },
    { id: 48, unit: "U5", en: "anime", ph: "[`ænəme]", zh: "(日本的)動畫片" },
    { id: 49, unit: "U5", en: "artist", ph: "[`ɑrtɪst]", zh: "藝術家" },
    { id: 50, unit: "U5", en: "college", ph: "[`kɑlɪdʒ]", zh: "大學" },
    { id: 51, unit: "U5", en: "attention", ph: "[ə`tɛnʃən]", zh: "注意" },

    // --- U4 單字 ---
    { id: 201, unit: "U4", en: "gate", ph: "[get]", zh: "大門" },
    { id: 202, unit: "U4", en: "file", ph: "[faɪl]", zh: "檔案" },
    { id: 203, unit: "U4", en: "quiz", ph: "[kwɪz]", zh: "小考" },
    { id: 204, unit: "U4", en: "blackboard", ph: "[`blæk,bɔrd]", zh: "黑板" },
    { id: 205, unit: "U4", en: "chalk", ph: "[tʃɔk]", zh: "粉筆" },
    { id: 206, unit: "U4", en: "screen", ph: "[skrin]", zh: "螢幕" },
    { id: 207, unit: "U4", en: "error", ph: "[`ɛrɚ]", zh: "錯誤" },
    { id: 208, unit: "U4", en: "button", ph: "[`bʌtṇ]", zh: "按鈕；鈕扣" },
    { id: 209, unit: "U4", en: "enter", ph: "[`ɛntɚ]", zh: "輸入；進入" },
    { id: 210, unit: "U4", en: "wake word", ph: "[`wek ,wɝd]", zh: "喚醒字詞" },
    { id: 211, unit: "U4", en: "whether", ph: "[`(h)wɛðɚ]", zh: "是否" },
    { id: 212, unit: "U4", en: "list", ph: "[lɪst]", zh: "清單；列出" },
    { id: 213, unit: "U4", en: "voice assistant", ph: "[`vɔɪs ə`sɪstənt]", zh: "語音助理" },
    { id: 214, unit: "U4", en: "machine", ph: "[mə`ʃin]", zh: "機器" },
    { id: 215, unit: "U4", en: "dozen", ph: "[`dʌzṇ]", zh: "(一)打" },
    { id: 216, unit: "U4", en: "refrigerator", ph: "[rɪ`frɪdʒə,retɚ]", zh: "冰箱" },
    { id: 217, unit: "U4", en: "upload", ph: "[ʌp`lod]", zh: "上傳" },
    { id: 218, unit: "U4", en: "e-mail", ph: "[`i,mel]", zh: "電子郵件" },
    { id: 219, unit: "U4", en: "key", ph: "[ki]", zh: "鑰匙" },
    { id: 220, unit: "U4", en: "shopkeeper", ph: "[`ʃɑp,kipɚ]", zh: "店主" },
    { id: 221, unit: "U4", en: "cellphone", ph: "[`sɛl,fon]", zh: "手機" },
    { id: 222, unit: "U4", en: "collect", ph: "[kə`lɛkt]", zh: "收集" },
    { id: 223, unit: "U4", en: "outside", ph: "[`aʊt`saɪd]", zh: "在外面；外面(的)" },
    { id: 224, unit: "U4", en: "wallet", ph: "[`wɑlɪt]", zh: "錢包" },
    { id: 225, unit: "U4", en: "couch", ph: "[kaʊtʃ]", zh: "沙發" },
    { id: 226, unit: "U4", en: "lamp", ph: "[læmp]", zh: "檯燈" },
    { id: 227, unit: "U4", en: "program", ph: "[`progræm]", zh: "節目" },
    { id: 228, unit: "U4", en: "modern", ph: "[`mɑdɚn]", zh: "現代的" },
    { id: 229, unit: "U4", en: "cross that bridge when one comes to it", ph: "[krɔs ðæt brɪdʒ hwen wʌn kʌmz tu ɪt]", zh: "船到橋頭自然直" },
    { id: 230, unit: "U4", en: "honey", ph: "[`hʌnɪ]", zh: "親愛的" },
    { id: 231, unit: "U4", en: "save", ph: "[sev]", zh: "儲存" },
    { id: 232, unit: "U4", en: "through", ph: "[θru]", zh: "透過；憑藉" },
    { id: 233, unit: "U4", en: "if", ph: "[ɪf]", zh: "是否" },
    { id: 234, unit: "U4", en: "not... anymore", ph: "[nɑt ... `ɛnɪmɔr]", zh: "不再..." },
    { id: 235, unit: "U4", en: "the cloud", ph: "[ðə `klaʊd]", zh: "雲端" },
    { id: 236, unit: "U4", en: "type", ph: "[taɪp]", zh: "打字" },
    { id: 237, unit: "U4", en: "stand for", ph: "[`stænd fɔr]", zh: "代表" },
    { id: 238, unit: "U4", en: "set", ph: "[sɛt]", zh: "設定" },
    { id: 239, unit: "U4", en: "shape", ph: "[ʃep]", zh: "塑造" },
    { id: 240, unit: "U4", en: "code", ph: "[kod]", zh: "碼" },
    { id: 241, unit: "U4", en: "connect", ph: "[kə`nɛkt]", zh: "連接" },
    { id: 242, unit: "U4", en: "product", ph: "[`prɑdʌkt]", zh: "產品" },
    { id: 243, unit: "U4", en: "everywhere", ph: "[`ɛvrɪ,hwɛr]", zh: "到處" },

    // --- U3 單字 ---
    { id: 301, unit: "U3", en: "senior center", ph: "[`sinjɚ ,sɛntɚ]", zh: "樂齡中心" },
    { id: 302, unit: "U3", en: "pleasure", ph: "[`plɛʒɚ]", zh: "愉快；榮幸" },
    { id: 303, unit: "U3", en: "attack", ph: "[ə`tæk]", zh: "攻擊" },
    { id: 304, unit: "U3", en: "toe", ph: "[to]", zh: "腳趾" },
    { id: 305, unit: "U3", en: "drop", ph: "[drɑp]", zh: "(使)落下；丟下" },
    { id: 306, unit: "U3", en: "land", ph: "[lænd]", zh: "落地；陸地" },
    { id: 307, unit: "U3", en: "puppy", ph: "[`pʌpɪ]", zh: "幼犬" },
    { id: 308, unit: "U3", en: "traffic", ph: "[`træfɪk]", zh: "車流(量)；交通" },
    { id: 309, unit: "U3", en: "middle", ph: "[`mɪd!]", zh: "中間" },
    { id: 310, unit: "U3", en: "carry", ph: "[`kærɪ]", zh: "攜帶" },
    { id: 311, unit: "U3", en: "note", ph: "[not]", zh: "紙條" },
    { id: 312, unit: "U3", en: "pocket", ph: "[`pɑkɪt]", zh: "口袋" },
    { id: 313, unit: "U3", en: "pray", ph: "[pre]", zh: "祈求；祈禱" },
    { id: 314, unit: "U3", en: "area", ph: "[`ɛrɪə]", zh: "區域" },
    { id: 315, unit: "U3", en: "glue", ph: "[glu]", zh: "膠水" },
    { id: 316, unit: "U3", en: "paste", ph: "[pest]", zh: "黏貼" },
    { id: 317, unit: "U3", en: "yard", ph: "[jɑrd]", zh: "庭院" },
    { id: 318, unit: "U3", en: "pipe", ph: "[paɪp]", zh: "水管" },
    { id: 319, unit: "U3", en: "bench", ph: "[bɛntʃ]", zh: "長凳；長椅" },
    { id: 320, unit: "U3", en: "badminton", ph: "[`bædmɪntən]", zh: "羽毛球" },
    { id: 321, unit: "U3", en: "tennis", ph: "[`tɛnɪs]", zh: "網球" },
    { id: 322, unit: "U3", en: "slide", ph: "[slaɪd]", zh: "滑梯" },
    { id: 323, unit: "U3", en: "seesaw", ph: "[`si,sɔ]", zh: "翹翹板" },
    { id: 324, unit: "U3", en: "swing", ph: "[swɪŋ]", zh: "鞦韆" },
    { id: 325, unit: "U3", en: "tool", ph: "[tul]", zh: "工具" },
    { id: 326, unit: "U3", en: "pot", ph: "[pɑt]", zh: "盆；鍋" },
    { id: 327, unit: "U3", en: "seed", ph: "[sid]", zh: "種子" },
    { id: 328, unit: "U3", en: "bake", ph: "[bek]", zh: "烘焙" },
    { id: 329, unit: "U3", en: "fill", ph: "[fɪl]", zh: "裝滿" },
    { id: 330, unit: "U3", en: "basket", ph: "[`bæskɪt]", zh: "籃子" },
    { id: 331, unit: "U3", en: "stranger", ph: "[`strendʒɚ]", zh: "陌生人" },
    { id: 332, unit: "U3", en: "boil", ph: "[bɔɪl]", zh: "煮沸" },
    { id: 333, unit: "U3", en: "smile", ph: "[smaɪl]", zh: "微笑" },
    { id: 334, unit: "U3", en: "pack", ph: "[pæk]", zh: "(一)包；副" },
    { id: 335, unit: "U3", en: "knock", ph: "[nɑk]", zh: "敲" },
    { id: 336, unit: "U3", en: "blow up", ph: "[,blo `ʌp]", zh: "爆炸" },
    { id: 337, unit: "U3", en: "in time", ph: "[,ɪn `taɪm]", zh: "及時" },
    { id: 338, unit: "U3", en: "fan", ph: "[fæn]", zh: "風扇" },
    { id: 339, unit: "U3", en: "show up", ph: "[,ʃo `ʌp]", zh: "出現" },
    { id: 340, unit: "U3", en: "hand", ph: "[hænd]", zh: "遞給" },
    { id: 341, unit: "U3", en: "volunteer", ph: "[,vɑlən`tɪr]", zh: "自願參加；志工" },
    { id: 342, unit: "U3", en: "war", ph: "[wɔr]", zh: "戰爭" },
    { id: 343, unit: "U3", en: "injure", ph: "[`ɪndʒɚ]", zh: "傷害" },
    { id: 344, unit: "U3", en: "bomb", ph: "[bɑm]", zh: "炸彈" },
    { id: 345, unit: "U3", en: "bark", ph: "[bɑrk]", zh: "狗吠" },
    { id: 346, unit: "U3", en: "address", ph: "[ə`drɛs ; `ædrɛs]", zh: "地址" },
    { id: 347, unit: "U3", en: "event", ph: "[ɪ`vɛnt]", zh: "事件" },
    { id: 348, unit: "U3", en: "brain", ph: "[bren]", zh: "頭腦" },
    { id: 349, unit: "U3", en: "damage", ph: "[`dæmɪdʒ]", zh: "損害" },

    // --- U2 單字 ---
    { id: 401, unit: "U2", en: "actor", ph: "[`æktɚ]", zh: "演員" },
    { id: 402, unit: "U2", en: "act", ph: "[ækt]", zh: "表演" },
    { id: 403, unit: "U2", en: "touch", ph: "[tʌtʃ]", zh: "觸動；碰觸" },
    { id: 404, unit: "U2", en: "heart", ph: "[hɑrt]", zh: "心；心臟" },
    { id: 405, unit: "U2", en: "surprise", ph: "[sɚ`praɪz]", zh: "(使)驚訝" },
    { id: 406, unit: "U2", en: "bored", ph: "[bɔrd]", zh: "感到無聊的" },
    { id: 407, unit: "U2", en: "hard-working", ph: "[,hɑrd`wɝkɪŋ]", zh: "勤奮的" },
    { id: 408, unit: "U2", en: "guess", ph: "[gɛs]", zh: "猜測" },
    { id: 409, unit: "U2", en: "several", ph: "[`sɛvərəl]", zh: "幾個的" },
    { id: 410, unit: "U2", en: "surprised", ph: "[sɚ`praɪzd]", zh: "感到驚訝的" },
    { id: 411, unit: "U2", en: "exciting", ph: "[ɪk`saɪtɪŋ]", zh: "令人興奮的；刺激的" },
    { id: 412, unit: "U2", en: "ghost", ph: "[gost]", zh: "鬼" },
    { id: 413, unit: "U2", en: "castle", ph: "[`kæs!]", zh: "城堡" },
    { id: 414, unit: "U2", en: "surprising", ph: "[sɚ`praɪzɪŋ]", zh: "令人驚訝的" },
    { id: 415, unit: "U2", en: "interested", ph: "[`ɪntərɪstɪd]", zh: "感興趣的" },
    { id: 416, unit: "U2", en: "boring", ph: "[`bɔrɪŋ]", zh: "無聊的" },
    { id: 417, unit: "U2", en: "download", ph: "[`daʊn,lod]", zh: "下載" },
    { id: 418, unit: "U2", en: "Internet", ph: "[`ɪntɚ,nɛt]", zh: "網路 (= Net [nɛt])" },
    { id: 419, unit: "U2", en: "set", ph: "[sɛt]", zh: "建立；樹立" },
    { id: 420, unit: "U2", en: "excited", ph: "[ɪk`saɪtɪd]", zh: "感到興奮的" },
    { id: 421, unit: "U2", en: "ticket", ph: "[`tɪkɪt]", zh: "票" },
    { id: 422, unit: "U2", en: "online", ph: "[`ɑn,laɪn]", zh: "在網上；線上的" },
    { id: 423, unit: "U2", en: "proud", ph: "[praʊd]", zh: "自豪的；驕傲的" },
    { id: 424, unit: "U2", en: "actress", ph: "[`æktrɪs]", zh: "女演員" },
    { id: 425, unit: "U2", en: "towel", ph: "[`taʊəl]", zh: "毛巾" },
    { id: 426, unit: "U2", en: "comb", ph: "[kom]", zh: "梳子；梳理" },
    { id: 427, unit: "U2", en: "bat", ph: "[bæt]", zh: "蝙蝠" },
    { id: 428, unit: "U2", en: "lie", ph: "[laɪ]", zh: "謊言；說謊" },
    { id: 429, unit: "U2", en: "fake", ph: "[fek]", zh: "假的；偽造的" },
    { id: 430, unit: "U2", en: "newspaper", ph: "[`njuz,pepɚ]", zh: "報紙" },
    { id: 431, unit: "U2", en: "nobody", ph: "[`nobɑdɪ]", zh: "無人" },
    { id: 432, unit: "U2", en: "anybody", ph: "[`ɛnɪ,bɑdɪ]", zh: "任何人 (= anyone)" },
    { id: 433, unit: "U2", en: "piece", ph: "[pis]", zh: "(一)則；片；張" },
    { id: 434, unit: "U2", en: "dig", ph: "[dɪg]", zh: "挖掘；尋找" },
    { id: 435, unit: "U2", en: "sentence", ph: "[`sɛntəns]", zh: "句子" },
    { id: 436, unit: "U2", en: "spell", ph: "[spɛl]", zh: "拼字" },
    { id: 437, unit: "U2", en: "trick", ph: "[trɪk]", zh: "騙；詭計" },
    { id: 438, unit: "U2", en: "I'll pass.", ph: "[aɪl `pæs]", zh: "不用了。" },
    { id: 439, unit: "U2", en: "book", ph: "[bʊk]", zh: "預訂；預約" },
    { id: 440, unit: "U2", en: "post", ph: "[post]", zh: "貼文；張貼" },
    { id: 441, unit: "U2", en: "right away", ph: "[,raɪt ə`we]", zh: "立刻；馬上" },
    { id: 442, unit: "U2", en: "hit", ph: "[hɪt]", zh: "點擊數" },
    { id: 443, unit: "U2", en: "talented", ph: "[`tæləntɪd]", zh: "有才華的" },
    { id: 444, unit: "U2", en: "award", ph: "[ə`wɔrd]", zh: "獎項" },
    { id: 445, unit: "U2", en: "pirated", ph: "[`paɪrətɪd]", zh: "盜版的" },
    { id: 446, unit: "U2", en: "horror", ph: "[`hɔrɚ]", zh: "恐怖" },
    { id: 447, unit: "U2", en: "spread", ph: "[sprɛd]", zh: "散播；(使)蔓延" },
    { id: 448, unit: "U2", en: "by design", ph: "[,baɪ dɪ`zaɪn]", zh: "故意；特意" },
    { id: 449, unit: "U2", en: "difference", ph: "[`dɪf(ə)rəns]", zh: "差別" },
    { id: 450, unit: "U2", en: "source", ph: "[sɔrs]", zh: "來源" },
    { id: 451, unit: "U2", en: "fact-checking", ph: "[`fækt,tʃɛkɪŋ]", zh: "查證事實的" },

    // --- U1 單字 ---
    { id: 501, unit: "U1", en: "yet", ph: "[jɛt]", zh: "還（沒）" },
    { id: 502, unit: "U1", en: "already", ph: "[ɔl`rɛdɪ]", zh: "已經" },
    { id: 503, unit: "U1", en: "diet", ph: "[`daɪət]", zh: "節食；飲食" },
    { id: 504, unit: "U1", en: "since", ph: "[sɪns]", zh: "自從" },
    { id: 505, unit: "U1", en: "photo", ph: "[`foto]", zh: "照片" },
    { id: 506, unit: "U1", en: "crazy", ph: "[`krezɪ]", zh: "荒唐的；瘋狂的" },
    { id: 507, unit: "U1", en: "as... as possible", ph: "[æz ... æz `pɑsəb!]", zh: "盡可能的..." },
    { id: 508, unit: "U1", en: "slim", ph: "[slɪm]", zh: "苗條的；微小的" },
    { id: 509, unit: "U1", en: "tip", ph: "[tɪp]", zh: "訣竅" },
    { id: 510, unit: "U1", en: "type", ph: "[taɪp]", zh: "類型" },
    { id: 511, unit: "U1", en: "ever", ph: "[`ɛvɚ]", zh: "曾經" },
    { id: 512, unit: "U1", en: "habit", ph: "[`hæbɪt]", zh: "習慣" },
    { id: 513, unit: "U1", en: "take action", ph: "[,tek `ækʃən]", zh: "採取行動" },
    { id: 514, unit: "U1", en: "choice", ph: "[tʃɔɪs]", zh: "選擇" },
    { id: 515, unit: "U1", en: "gym", ph: "[dʒɪm]", zh: "健身房；體育館" },
    { id: 516, unit: "U1", en: "abroad", ph: "[ə`brɔd]", zh: "到國外" },
    { id: 517, unit: "U1", en: "cheat", ph: "[tʃit]", zh: "作弊；欺騙" },
    { id: 518, unit: "U1", en: "copy", ph: "[`kɑpɪ]", zh: "抄襲；複製" },
    { id: 519, unit: "U1", en: "race", ph: "[res]", zh: "速度競賽" },
    { id: 520, unit: "U1", en: "letter", ph: "[`lɛtɚ]", zh: "信" },
    { id: 521, unit: "U1", en: "teenager", ph: "[`tin,edʒɚ]", zh: "青少年" },
    { id: 522, unit: "U1", en: "senior high school", ph: "[`sinjɚ `haɪ ,skul]", zh: "高中" },
    { id: 523, unit: "U1", en: "understand", ph: "[,ʌndɚ`stænd]", zh: "瞭解" },
    { id: 524, unit: "U1", en: "drum", ph: "[drʌm]", zh: "鼓" },
    { id: 525, unit: "U1", en: "joy", ph: "[dʒɔɪ]", zh: "樂趣；喜悅" },
    { id: 526, unit: "U1", en: "pop", ph: "[pɑp]", zh: "流行音樂" },
    { id: 527, unit: "U1", en: "lately", ph: "[`letlɪ]", zh: "最近" },
    { id: 528, unit: "U1", en: "angry", ph: "[`æŋgrɪ]", zh: "生氣的" },
    { id: 529, unit: "U1", en: "serious", ph: "[`sɪrɪəs]", zh: "嚴重的" },
    { id: 530, unit: "U1", en: "interest", ph: "[`ɪnt(ə)rɪst]", zh: "興趣；使感興趣" },
    { id: 531, unit: "U1", en: "garbage", ph: "[`gɑrbɪdʒ]", zh: "垃圾" },
    { id: 532, unit: "U1", en: "unhappy", ph: "[ʌn`hæpɪ]", zh: "不快樂的" },
    { id: 533, unit: "U1", en: "wish", ph: "[wɪʃ]", zh: "祝福" },
    { id: 534, unit: "U1", en: "envelope", ph: "[`ɛnvə,lop]", zh: "信封" },
    { id: 535, unit: "U1", en: "stamp", ph: "[stæmp]", zh: "郵票" },
    { id: 536, unit: "U1", en: "be all ears", ph: "[bi ɔl `ɪrz]", zh: "洗耳恭聽" },
    { id: 537, unit: "U1", en: "at least", ph: "[æt `list]", zh: "至少" },
    { id: 538, unit: "U1", en: "You got it.", ph: "[ju `gɑt ɪt]", zh: "沒錯。" },
    { id: 539, unit: "U1", en: "stay in shape", ph: "[,ste ɪn `ʃep]", zh: "保持健康" },
    { id: 540, unit: "U1", en: "star", ph: "[stɑr]", zh: "明星" },
    { id: 541, unit: "U1", en: "call", ph: "[kɔl]", zh: "稱呼" },
    { id: 542, unit: "U1", en: "talk... into", ph: "[,tɔk `ɪntə]", zh: "說服（某人）做..." },
    { id: 543, unit: "U1", en: "skip", ph: "[skɪp]", zh: "省略" },
    { id: 544, unit: "U1", en: "appearance", ph: "[ə`pɪrəns]", zh: "外表；外觀" },
    { id: 545, unit: "U1", en: "weight", ph: "[wet]", zh: "體重" },
    { id: 546, unit: "U1", en: "balanced", ph: "[`bælənst]", zh: "均衡的" },
    { id: 547, unit: "U1", en: "mood", ph: "[mud]", zh: "心情" },
    { id: 548, unit: "U1", en: "exam", ph: "[ɪg`zæm]", zh: "考試" },
    { id: 549, unit: "U1", en: "feeling", ph: "[`filɪŋ]", zh: "情緒；感覺" },

    // ==========================================
    //               第六冊 (Book 6)
    // ==========================================

    // --- U1 單字 ---
    // 請將圖片中的單字填入這裡，範例如下：
    { id: 601, unit: "B6U1", en: "word", ph: "[wɝd]", zh: "單字 (範例)" },
    // { id: 602, unit: "B6U1", en: "...", ph: "[...]", zh: "..." },
];
